trigger:
- main

variables:

  webAppName: 'tiptipfront'

  # Environments
  prodEnvironment: 'tiptipfront-prod'
  recetteEnvironment: 'tiptipfront-recette'

  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.14.0'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build --if-present
      displayName: 'npm install, build'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/projectdsp/browser'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

  # Prod

- stage: DeployProd
  displayName: Deploy Prod stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployProd
    displayName: Deploy Prod
    environment: $(prodEnvironment)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: tiptipfront (Prod)'
            inputs:
              azureSubscription: 'Azure subscription 1'
              appType: 'webAppLinux'
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              runtimeStack: 'PHP|7.4'

  # Preprod
- stage: DeployRecette
  displayName: Deploy Recette stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployRecette
    displayName: Deploy Recette
    environment: $(recetteEnvironment)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: tiptipfront (Recette)'
            inputs:
              azureSubscription: 'Azure subscription 1'
              appType: 'webAppLinux'
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              runtimeStack: 'PHP|7.4'
